from _typeshed import Incomplete

small_trailing: Incomplete

def giant_steps(start, target, n: int = 2): ...
def rshift(x, n): ...
def lshift(x, n): ...

rshift: Incomplete
lshift: Incomplete

def python_trailing(n): ...
def gmpy_trailing(n): ...

powers: Incomplete

def python_bitcount(n): ...
def gmpy_bitcount(n): ...
def sage_trailing(n): ...

bitcount = gmpy_bitcount
trailing = gmpy_trailing
sage_bitcount: Incomplete
bitcount = sage_bitcount
trailing = sage_trailing
bitcount = python_bitcount
trailing = python_trailing
trailtable: Incomplete
bctable: Incomplete

def bin_to_radix(x, xbits, base, bdigits): ...

stddigits: str

def small_numeral(n, base: int = 10, digits="0123456789abcdefghijklmnopqrstuvwxyz"): ...
def numeral_python(n, base: int = 10, size: int = 0, digits="0123456789abcdefghijklmnopqrstuvwxyz"): ...
def numeral_gmpy(n, base: int = 10, size: int = 0, digits="0123456789abcdefghijklmnopqrstuvwxyz"): ...

numeral = numeral_gmpy
numeral = numeral_python

def isqrt_small_python(x): ...
def isqrt_fast_python(x): ...
def sqrtrem_python(x): ...
def isqrt_python(x): ...
def sqrt_fixed(x, prec): ...

sqrt_fixed2 = sqrt_fixed
isqrt_small: Incomplete
isqrt_fast: Incomplete
isqrt: Incomplete
sqrtrem: Incomplete
isqrt_small = isqrt_small_python
isqrt_fast = isqrt_fast_python
isqrt = isqrt_python
sqrtrem = sqrtrem_python

def ifib(n, _cache={}): ...

MAX_FACTORIAL_CACHE: int

def ifac(n, memo={0: 1, 1: 1}): ...
def ifac2(n, memo_pair=[{0: 1}, {1: 1}]): ...

ifac: Incomplete
ifib: Incomplete

def list_primes(n): ...

small_odd_primes: Incomplete
small_odd_primes_set: Incomplete

def isprime(n): ...
def moebius(n): ...
def gcd(*args): ...

MAX_EULER_CACHE: int

def eulernum(m, _cache={0: 1}): ...
def stirling1(n, k): ...
def stirling2(n, k): ...
