def gammaprod(ctx, a, b, _infsign: bool = False): ...
def beta(ctx, x, y): ...
def binomial(ctx, n, k): ...
def rf(ctx, x, n): ...
def ff(ctx, x, n): ...
def fac2(ctx, x): ...
def barnesg(ctx, z): ...
def superfac(ctx, z): ...
def hyperfac(ctx, z): ...
