def hermite(ctx, n, z, **kwargs): ...
def pcfd(ctx, n, z, **kwargs): ...
def pcfu(ctx, a, z, **kwargs): ...
def pcfv(ctx, a, z, **kwargs): ...
def pcfw(ctx, a, z, **kwargs): ...
def gegenbauer(ctx, n, a, z, **kwargs): ...
def jacobi(ctx, n, a, b, x, **kwargs): ...
def laguerre(ctx, n, a, z, **kwargs): ...
def legendre(ctx, n, x, **kwargs): ...
def legenp(ctx, n, m, z, type: int = 2, **kwargs): ...
def legenq(ctx, n, m, z, type: int = 2, **kwargs): ...
def chebyt(ctx, n, x, **kwargs): ...
def chebyu(ctx, n, x, **kwargs): ...
def spherharm(ctx, l, m, theta, phi, **kwargs): ...
