from _typeshed import Incomplete

def qp(ctx, a, q: Incomplete | None = None, n: Incomplete | None = None, **kwargs): ...
def qgamma(ctx, z, q, **kwargs): ...
def qfac(ctx, z, q, **kwargs): ...
def qhyper(ctx, a_s, b_s, q, z, **kwargs): ...
