class RSCache:
    def __init__(ctx) -> None: ...

def coef(ctx, J, eps): ...
def aux_M_Fp(ctx, xA, xeps4, a, xB1, xL): ...
def aux_J_needed(ctx, xA, xeps4, a, xB1, xM): ...
def Rzeta_simul(ctx, s, der: int = 0): ...
def Rzeta_set(ctx, s, derivatives=[0]): ...
def z_half(ctx, t, der: int = 0): ...
def zeta_half(ctx, s, k: int = 0): ...
def zeta_offline(ctx, s, k: int = 0): ...
def z_offline(ctx, w, k: int = 0): ...
def rs_zeta(ctx, s, derivative: int = 0, **kwargs): ...
def rs_z(ctx, w, derivative: int = 0): ...
