class MatrixCalculusMethods:
    def expm(ctx, A, method: str = "taylor"): ...
    def cosm(ctx, A): ...
    def sinm(ctx, A): ...
    def sqrtm(ctx, A, _may_rotate: int = 2): ...
    def logm(ctx, A): ...
    def powm(ctx, A, r): ...
