from _typeshed import Incomplete
from collections.abc import Generator

def chebcoeff(ctx, f, a, b, j, N): ...
def chebT(ctx, a: int = 1, b: int = 0) -> Generator[Incomplete, None, None]: ...
def chebyfit(ctx, f, interval, N, error: bool = False): ...
def fourier(ctx, f, interval, N): ...
def fourierval(ctx, series, interval, x): ...
