from _typeshed import Incomplete

class ODEMethods: ...

def ode_taylor(ctx, derivs, x0, y0, tol_prec, n): ...
def odefun(
    ctx, F, x0, y0, tol: Incomplete | None = None, degree: Incomplete | None = None, method: str = "taylor", verbose: bool = False
): ...
