"""
This type stub file was generated by pyright.
"""

import sys

"""
python runtests.py -py
  Use py.test to run tests (more useful for debugging)

python runtests.py -coverage
  Generate test coverage report. Statistics are written to /tmp

python runtests.py -profile
  Generate profile stats (this is much slower)

python runtests.py -nogmpy
  Run tests without using GMPY even if it exists

python runtests.py -strict
  Enforce extra tests in normalize()

python runtests.py -local
  Insert '../..' at the beginning of sys.path to use local mpmath

python runtests.py -skip ...
  Skip tests from the listed modules

Additional arguments are used to filter the tests to run. Only files that have
one of the arguments in their name are executed.

"""
profile = ...
if "-profile" in sys.argv:
    profile = ...
coverage = ...
if "-coverage" in sys.argv:
    coverage = ...
if "-nogmpy" in sys.argv:
    ...
if "-strict" in sys.argv:
    ...
if "-local" in sys.argv:
    importdir = ...
else:
    importdir = ...
testdir = ...
def testit(importdir=..., testdir=..., exit_on_fail=...): # -> None:
    """Run all tests in testdir while importing from importdir."""
    ...

if __name__ == '__main__':
    ...
