"""
This type stub file was generated by pyright.
"""

from .functions import defun, defun_wrapped

@defun
def erf(ctx, z): # -> Any:
    ...

@defun
def erfc(ctx, z): # -> Any:
    ...

@defun
def square_exp_arg(ctx, z, mult=..., reciprocal=...):
    ...

@defun_wrapped
def erfi(ctx, z):
    ...

@defun_wrapped
def erfinv(ctx, x):
    ...

@defun_wrapped
def npdf(ctx, x, mu=..., sigma=...):
    ...

@defun_wrapped
def ncdf(ctx, x, mu=..., sigma=...):
    ...

@defun_wrapped
def betainc(ctx, a, b, x1=..., x2=..., regularized=...): # -> Literal[0]:
    ...

@defun
def gammainc(ctx, z, a=..., b=..., regularized=...): # -> None:
    ...

@defun_wrapped
def expint(ctx, n, z): # -> int:
    ...

@defun_wrapped
def li(ctx, z, offset=...):
    ...

@defun
def ei(ctx, z):
    ...

@defun
def e1(ctx, z):
    ...

@defun
def ci(ctx, z):
    ...

@defun
def si(ctx, z):
    ...

@defun_wrapped
def chi(ctx, z):
    ...

@defun_wrapped
def shi(ctx, z):
    ...

@defun_wrapped
def fresnels(ctx, z):
    ...

@defun_wrapped
def fresnelc(ctx, z):
    ...

