"""
This type stub file was generated by pyright.
"""

from .functions import defun, defun_wrapped

@defun
def gammaprod(ctx, a, b, _infsign=...):
    ...

@defun
def beta(ctx, x, y):
    ...

@defun
def binomial(ctx, n, k):
    ...

@defun
def rf(ctx, x, n):
    ...

@defun
def ff(ctx, x, n):
    ...

@defun_wrapped
def fac2(ctx, x):
    ...

@defun_wrapped
def barnesg(ctx, z):
    ...

@defun
def superfac(ctx, z):
    ...

@defun_wrapped
def hyperfac(ctx, z):
    ...

