"""
This type stub file was generated by pyright.
"""

from .functions import defun_wrapped

@defun_wrapped
def squarew(ctx, t, amplitude=..., period=...):
    ...

@defun_wrapped
def trianglew(ctx, t, amplitude=..., period=...):
    ...

@defun_wrapped
def sawtoothw(ctx, t, amplitude=..., period=...):
    ...

@defun_wrapped
def unit_triangle(ctx, t, amplitude=...):
    ...

@defun_wrapped
def sigmoid(ctx, t, amplitude=...):
    ...

